name: Bump version

on: [ workflow_dispatch ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    container: laughlamz/docker-python-kubectl
    steps:
      - uses: actions/checkout@v3
      - name: bump
        run: bumpver update --patch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: '${{ secrets.AUTORELEASE_TOKEN }}'
          branch: chore/bump-version-${{ steps.date.outputs.date }}
          base: main
          title: Bump version ${{ steps.date.outputs.date }}
          commit-message: Bump version ${{ steps.date.outputs.date }}
