name: Bump version

on: [ workflow_dispatch ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    container: laughlamz/docker-python-kubectl
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        id: bump
        run: |
          bumpver update --patch --no-commit
          eval $(bumpver show -n --env)
          echo $CURRENT_VERSION
          echo "current-version=$$CURRENT_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: '${{ secrets.AUTORELEASE_TOKEN }}'
          branch: chore/bump-version-${{ steps.bump.outputs.current-version }}
          base: main
          title: Bump version ${{ steps.bump.outputs.current-version }}
          commit-message: Bump version ${{ steps.bump.outputs.current-version }}
