name: Bump version

on: [ workflow_dispatch ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    container: laughlamz/docker-python-kubectl
    steps:
      - uses: actions/checkout@v3
      - name: Install git
        run: |
          apt update
          apt install -y git
          git config --global user.name "Son Lam"
          git config --global user.email laughlamz@gmail.com
          git config --global --add safe.directory /__w/django-vnpay/django-vnpay
      - name: Bump version
        id: bump
        run: |
          pip install bumpver
          bumpver update --patch --no-commit
          eval $(bumpver show -n --env)
          echo $CURRENT_VERSION
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          git status
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: '${{ secrets.AUTORELEASE_TOKEN }}'
          branch: chore/bump-version-${{ steps.bump.outputs.current-version }}
          base: main
          title: Bump version ${{ steps.bump.outputs.current-version }}
          commit-message: Bump version ${{ steps.bump.outputs.current-version }}
